# Generated by Django 4.2.6 on 2023-10-14 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoreInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storeName', models.CharField(max_length=255)),
                ('storeTagLine', models.CharField(blank=True, max_length=255, null=True)),
                ('contactEmail', models.CharField(max_length=255)),
                ('contactPhone', models.CharField(max_length=255)),
                ('contactName', models.CharField(blank=True, max_length=255, null=True)),
                ('ownerName', models.CharField(max_length=255)),
                ('address01', models.CharField(blank=True, max_length=255)),
                ('address02', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('state', models.CharField(blank=True, max_length=255)),
                ('zip', models.CharField(blank=True, max_length=255)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=255)),
                ('lastName', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StoreColors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headerBG', models.CharField(blank=True, max_length=255, null=True)),
                ('navBG', models.CharField(blank=True, max_length=255, null=True)),
                ('navFont', models.CharField(blank=True, max_length=255, null=True)),
                ('mainBG', models.CharField(blank=True, max_length=255, null=True)),
                ('mainFont', models.CharField(blank=True, max_length=255, null=True)),
                ('productBG', models.CharField(blank=True, max_length=255, null=True)),
                ('productFont', models.CharField(blank=True, max_length=255, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theStore', to='themesApp.storeinfo')),
            ],
        ),
    ]
