# Generated by Django 4.2.6 on 2023-10-14 02:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customerApp', '0001_initial'),
        ('storeApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderNum', models.CharField(max_length=255, unique=True)),
                ('itemCount', models.IntegerField(blank=True, null=True)),
                ('orderTotal', models.CharField(blank=True, max_length=255, null=True)),
                ('orderStatus', models.CharField(choices=[('New', 'Newly Placed'), ('Pending', 'In discussion between Customer and Owner'), ('In Progress', 'Item is being created'), ('Order Items Created', 'All items in order have been created'), ('Shipped', 'Item has been shipped'), ('Delivered', 'Item has been delivered'), ('Rejected', 'Order was Rejected'), ('Returned', 'Order was Returned'), ('Archived', 'Order was archived')], default='New', max_length=255)),
                ('paymentStatus', models.CharField(choices=[('New', 'New Order payment terms not set yet'), ('Paid', 'Order is fully Paid for'), ('Payment Plan', 'Order is on a payment plan that in still ongoing'), ('Billed', 'Final Price determined and sent to customer'), ('Unpaid', 'Order remains unpaid'), ('On Hold', 'Order is on hold awaiting terms')], default='New', max_length=255)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theCustomer', to='customerApp.customer')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('total', models.CharField(max_length=255)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('orderNum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theOrder', to='orderApp.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theProd', to='storeApp.product')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderDate', models.DateField(default=datetime.datetime.today)),
                ('pdf', models.FileField(upload_to='invoices')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('cart', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orderApp.order')),
                ('theCustomer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custOrder', to='customerApp.customer')),
            ],
        ),
    ]
