# Generated by Django 4.2.6 on 2023-11-05 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='itemCount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderTotal',
            field=models.CharField(blank=True, default=0, max_length=255, null=True),
        ),
    ]
