# Generated by Django 4.2.6 on 2023-10-12 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0002_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='address01',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='address02',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='age',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='state',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='zip',
        ),
    ]
