# Generated by Django 4.2.6 on 2023-10-22 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customerApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomerProfile',
            new_name='Profile',
        ),
    ]
