# Generated by Django 4.2.6 on 2023-10-23 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerApp', '0002_rename_customerprofile_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='cartoonCar06.png', upload_to='profiles'),
        ),
    ]
